import { randomBytes,randomInt,randomUUID,scryptSync,timingSafeEqual } from "node:crypto";
import path from "node:path";
import Database from "better-sqlite3";
import type { User } from "@clipx/contracts/schema";
import type { Account,AppNotification,BankCard,BankingOverview,BankTransaction,Beneficiary,CardDetails,CreateInternalTransfer,CreatePeerTransfer,CreateTransfer,InternalTransferReceipt,PeerRecipient,PeerTransferReceipt,TransactionDetails,UpdateCard } from "@clipx/contracts/banking";
import type { AdminCustomer,AdminCustomerDetails,AdminStats,AdminTransaction,AdminTransactionDetails,CreateAdminAccount,CreateAdminCard,CreateAdminCustomer,UpdateAdminAccount,UpdateAdminUser } from "@clipx/contracts/admin";
import type { AccountSettings,ChangePassword,UpdatePreferences,UpdateProfile } from "@clipx/contracts/settings";
import type { LocalAuthUser } from "@clipx/contracts/auth";
import type { SupportMessage,SupportSenderRole } from "@clipx/contracts/support";
import type { AvatarFile,AvatarUpload,IStorage } from "./storage.js";
import { config } from "./config.js";
import { decryptPan,encryptPan,fingerprintPan,generateExpiry,generateMastercardPan,generateSecurityCode,generateVisaPan } from "./card-security.js";

type UserRow={id:string;email:string;first_name:string;last_name:string;profile_image_url:string|null;is_admin:number;is_active:number;created_at:string;updated_at:string;last_active_at:string};
type AccountRow={id:string;name:string;type:"checking"|"savings";account_number:string|null;masked_number:string;currency:"USD";balance_cents:number;available_balance_cents:number;interest_rate_bps:number|null};
type TransactionRow={id:string;account_id:string;internal_transfer_id?:string|null;peer_transfer_id?:string|null;description:string;merchant:string;category:BankTransaction["category"];amount_cents:number;direction:BankTransaction["direction"];status:BankTransaction["status"];reference:string;created_at:string};
type TransactionDetailsRow=TransactionRow&{account_name:string;account_type:Account["type"];account_masked_number:string};
type CardRow={id:string;account_id:string;holder_name:string;last_four:string;network:BankCard["network"];type:BankCard["type"];status:BankCard["status"];spending_limit_cents:number;expires:string;pan_ciphertext:string|null;pan_iv:string|null;pan_auth_tag:string|null;pan_fingerprint:string|null;created_at:string};
type BeneficiaryRow={id:string;name:string;bank_name:string;masked_account:string;initials:string};
type PeerRecipientRow=AccountRow&{user_id:string;first_name:string;last_name:string};
type NotificationRow={id:string;type:"card_issued"|"support_message";title:string;message:string;resource_id:string|null;is_read:number;created_at:string};
type AvatarRow={content_type:"image/jpeg"|"image/png"|"image/webp";image_data:Buffer;updated_at:string};
type SupportMessageRow={id:string;customer_user_id:string;sender_user_id:string;sender_role:SupportSenderRole;body:string;read_by_customer:number;read_by_admin:number;created_at:string;sender_name:string};
type AdminCardInput=Omit<CreateAdminCard,"network"> & {network?:CreateAdminCard["network"]};

const cents=(value:number)=>Math.round(value*100);
const dollars=(value:number)=>value/100;
const accountHolderName=(firstName:string,lastName:string)=>`${firstName.trim()} ${lastName.trim()}`.trim();
const createPasswordHash=(password:string,salt=randomBytes(16).toString("hex"))=>({salt,hash:scryptSync(password,salt,64).toString("hex")});
const passwordMatches=(password:string,salt:string,hash:string)=>{const actual=scryptSync(password,salt,64);const expected=Buffer.from(hash,"hex");return actual.length===expected.length&&timingSafeEqual(actual,expected);};
const toAccount=(row:AccountRow):Account=>({id:row.id,name:row.name,type:row.type,...(row.account_number?{accountNumber:row.account_number}:{}),maskedNumber:row.masked_number,currency:row.currency,balance:dollars(row.balance_cents),availableBalance:dollars(row.available_balance_cents),...(row.interest_rate_bps===null?{}:{interestRate:row.interest_rate_bps/100})});
const generateAccountNumber=()=>randomInt(1_000_000_000,10_000_000_000).toString();
const toTransaction=(row:TransactionRow):BankTransaction=>({id:row.id,accountId:row.account_id,description:row.description,merchant:row.merchant,category:row.category,amount:dollars(row.amount_cents),direction:row.direction,status:row.status,reference:row.reference,createdAt:row.created_at});
const toTransactionDetails=(row:TransactionDetailsRow):TransactionDetails=>({id:row.id,description:row.description,merchant:row.merchant,category:row.category,amount:dollars(row.amount_cents),direction:row.direction,status:row.status,reference:row.reference,createdAt:row.created_at,accountName:row.account_name,accountType:row.account_type,accountMaskedNumber:row.account_masked_number,transferKind:row.peer_transfer_id?"account_number":row.internal_transfer_id?"between_accounts":"standard"});
const toCard=(row:CardRow):BankCard=>({id:row.id,accountId:row.account_id,holderName:row.holder_name,lastFour:row.last_four,network:row.network,type:row.type,status:row.status,spendingLimit:dollars(row.spending_limit_cents),expires:row.expires,hasSecureDetails:Boolean(row.pan_ciphertext&&row.pan_iv&&row.pan_auth_tag),issuedAt:row.created_at});
const toNotification=(row:NotificationRow):AppNotification=>({id:row.id,type:row.type,title:row.title,message:row.message,resourceId:row.resource_id,isRead:Boolean(row.is_read),createdAt:row.created_at});
const toSupportMessage=(row:SupportMessageRow,viewerRole:SupportSenderRole):SupportMessage=>({id:row.id,customerUserId:row.customer_user_id,senderUserId:row.sender_user_id,senderRole:row.sender_role,senderName:row.sender_name,body:row.body,isRead:Boolean(viewerRole==="customer"?row.read_by_customer:row.read_by_admin),createdAt:row.created_at});
const requireCardDataKey=()=>{if(!config.cardDataEncryptionKey)throw Object.assign(new Error("Card security is not configured"),{status:503});return config.cardDataEncryptionKey;};

export class SQLiteStorage implements IStorage{
  readonly kind="sqlite" as const;
  readonly databasePath:string;
  private readonly db:Database.Database;

  constructor(databasePath=process.env.CLIPX_DATABASE_PATH||path.resolve(import.meta.dirname,"../../../clipx.db")){
    this.databasePath=databasePath;
    this.db=new Database(databasePath);
    this.db.pragma("journal_mode = WAL");
    this.db.pragma("foreign_keys = ON");
    this.migrate();
    this.ensureLegacyCredentials();
  }

  private migrate(){this.db.exec(`
    CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,first_name TEXT NOT NULL,last_name TEXT NOT NULL,profile_image_url TEXT,is_admin INTEGER NOT NULL DEFAULT 0,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,last_active_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS accounts (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN ('checking','savings')),account_number TEXT UNIQUE CHECK(account_number IS NULL OR (length(account_number)=10 AND account_number NOT GLOB '*[^0-9]*')),masked_number TEXT NOT NULL,currency TEXT NOT NULL DEFAULT 'USD',balance_cents INTEGER NOT NULL,available_balance_cents INTEGER NOT NULL,interest_rate_bps INTEGER);
    CREATE TABLE IF NOT EXISTS internal_transfers (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,source_account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,destination_account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,amount_cents INTEGER NOT NULL CHECK(amount_cents>0),note TEXT NOT NULL,reference TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'completed' CHECK(status='completed'),created_at TEXT NOT NULL,CHECK(source_account_id<>destination_account_id));
    CREATE TABLE IF NOT EXISTS peer_transfers (id TEXT PRIMARY KEY,sender_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,source_account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,recipient_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,destination_account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,amount_cents INTEGER NOT NULL CHECK(amount_cents>0),note TEXT NOT NULL,reference TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'completed' CHECK(status='completed'),created_at TEXT NOT NULL,CHECK(sender_user_id<>recipient_user_id),CHECK(source_account_id<>destination_account_id));
    CREATE TABLE IF NOT EXISTS transactions (id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,internal_transfer_id TEXT REFERENCES internal_transfers(id) ON DELETE SET NULL,peer_transfer_id TEXT REFERENCES peer_transfers(id) ON DELETE SET NULL,description TEXT NOT NULL,merchant TEXT NOT NULL,category TEXT NOT NULL,amount_cents INTEGER NOT NULL CHECK(amount_cents>0),direction TEXT NOT NULL CHECK(direction IN ('credit','debit')),status TEXT NOT NULL CHECK(status IN ('completed','pending','failed')),reference TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL,CHECK(internal_transfer_id IS NULL OR peer_transfer_id IS NULL));
    CREATE TABLE IF NOT EXISTS cards (id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,holder_name TEXT NOT NULL,last_four TEXT NOT NULL,network TEXT NOT NULL DEFAULT 'Mastercard',type TEXT NOT NULL CHECK(type IN ('physical','virtual')),status TEXT NOT NULL CHECK(status IN ('active','frozen')),spending_limit_cents INTEGER NOT NULL,expires TEXT NOT NULL,pan_ciphertext TEXT,pan_iv TEXT,pan_auth_tag TEXT,pan_fingerprint TEXT,created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS beneficiaries (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,bank_name TEXT NOT NULL,masked_account TEXT NOT NULL,initials TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS cash_flow (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,month TEXT NOT NULL,sort_order INTEGER NOT NULL,income_cents INTEGER NOT NULL,spending_cents INTEGER NOT NULL,PRIMARY KEY(user_id,month));
    CREATE TABLE IF NOT EXISTS user_preferences (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,transaction_alerts INTEGER NOT NULL DEFAULT 1,monthly_summary INTEGER NOT NULL DEFAULT 1,show_balances INTEGER NOT NULL DEFAULT 1);
    CREATE TABLE IF NOT EXISTS local_credentials (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS security_audit_events (id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id) ON DELETE SET NULL,event_type TEXT NOT NULL,resource_id TEXT,ip_address TEXT,created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS user_avatars (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,content_type TEXT NOT NULL CHECK(content_type IN ('image/jpeg','image/png','image/webp')),image_data BLOB NOT NULL,byte_size INTEGER NOT NULL CHECK(byte_size>0 AND byte_size<=2097152),updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,type TEXT NOT NULL CHECK(type IN ('card_issued','support_message')),title TEXT NOT NULL,message TEXT NOT NULL,resource_id TEXT,is_read INTEGER NOT NULL DEFAULT 0 CHECK(is_read IN (0,1)),created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS support_messages (id TEXT PRIMARY KEY,customer_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,sender_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,sender_role TEXT NOT NULL CHECK(sender_role IN ('customer','admin')),body TEXT NOT NULL CHECK(length(body) BETWEEN 1 AND 2000),read_by_customer INTEGER NOT NULL DEFAULT 0 CHECK(read_by_customer IN (0,1)),read_by_admin INTEGER NOT NULL DEFAULT 0 CHECK(read_by_admin IN (0,1)),created_at TEXT NOT NULL);
    CREATE INDEX IF NOT EXISTS idx_accounts_user ON accounts(user_id);CREATE INDEX IF NOT EXISTS idx_transactions_account_date ON transactions(account_id,created_at DESC);CREATE INDEX IF NOT EXISTS idx_beneficiaries_user ON beneficiaries(user_id);CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expires_at);
  `);
    const notificationSchema=this.db.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name='notifications'").get() as {sql:string}|undefined;
    if(notificationSchema&&!notificationSchema.sql.includes("support_message")){
      this.db.exec("ALTER TABLE notifications RENAME TO notifications_legacy; CREATE TABLE notifications (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,type TEXT NOT NULL CHECK(type IN ('card_issued','support_message')),title TEXT NOT NULL,message TEXT NOT NULL,resource_id TEXT,is_read INTEGER NOT NULL DEFAULT 0 CHECK(is_read IN (0,1)),created_at TEXT NOT NULL); INSERT INTO notifications SELECT * FROM notifications_legacy; DROP TABLE notifications_legacy;");
    }
    const columns=this.db.prepare("PRAGMA table_info(accounts)").all() as Array<{name:string}>;
    if(!columns.some((column)=>column.name==="account_number"))this.db.exec("ALTER TABLE accounts ADD COLUMN account_number TEXT");
    const transactionColumns=this.db.prepare("PRAGMA table_info(transactions)").all() as Array<{name:string}>;
    if(!transactionColumns.some((column)=>column.name==="internal_transfer_id"))this.db.exec("ALTER TABLE transactions ADD COLUMN internal_transfer_id TEXT REFERENCES internal_transfers(id) ON DELETE SET NULL");
    if(!transactionColumns.some((column)=>column.name==="peer_transfer_id"))this.db.exec("ALTER TABLE transactions ADD COLUMN peer_transfer_id TEXT REFERENCES peer_transfers(id) ON DELETE SET NULL");
    const cardColumns=this.db.prepare("PRAGMA table_info(cards)").all() as Array<{name:string}>;
    if(!cardColumns.some((column)=>column.name==="pan_ciphertext"))this.db.exec("ALTER TABLE cards ADD COLUMN pan_ciphertext TEXT");
    if(!cardColumns.some((column)=>column.name==="pan_iv"))this.db.exec("ALTER TABLE cards ADD COLUMN pan_iv TEXT");
    if(!cardColumns.some((column)=>column.name==="pan_auth_tag"))this.db.exec("ALTER TABLE cards ADD COLUMN pan_auth_tag TEXT");
    if(!cardColumns.some((column)=>column.name==="pan_fingerprint"))this.db.exec("ALTER TABLE cards ADD COLUMN pan_fingerprint TEXT");
    if(!cardColumns.some((column)=>column.name==="created_at")){this.db.exec("ALTER TABLE cards ADD COLUMN created_at TEXT");this.db.prepare("UPDATE cards SET created_at=? WHERE created_at IS NULL").run(new Date().toISOString());}
    this.db.exec(`
      CREATE UNIQUE INDEX IF NOT EXISTS idx_accounts_account_number ON accounts(account_number) WHERE account_number IS NOT NULL;
      CREATE INDEX IF NOT EXISTS idx_internal_transfers_user_created ON internal_transfers(user_id,created_at DESC);
      CREATE INDEX IF NOT EXISTS idx_transactions_internal_transfer ON transactions(internal_transfer_id) WHERE internal_transfer_id IS NOT NULL;
      CREATE INDEX IF NOT EXISTS idx_peer_transfers_sender_created ON peer_transfers(sender_user_id,created_at DESC);
      CREATE INDEX IF NOT EXISTS idx_peer_transfers_recipient_created ON peer_transfers(recipient_user_id,created_at DESC);
      CREATE INDEX IF NOT EXISTS idx_transactions_peer_transfer ON transactions(peer_transfer_id) WHERE peer_transfer_id IS NOT NULL;
      CREATE UNIQUE INDEX IF NOT EXISTS idx_cards_pan_fingerprint ON cards(pan_fingerprint) WHERE pan_fingerprint IS NOT NULL;
      CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id,created_at DESC);
      CREATE INDEX IF NOT EXISTS idx_support_messages_customer_created ON support_messages(customer_user_id,created_at);
      CREATE TRIGGER IF NOT EXISTS accounts_account_number_format_insert BEFORE INSERT ON accounts
      WHEN NEW.account_number IS NOT NULL AND (length(NEW.account_number)<>10 OR NEW.account_number GLOB '*[^0-9]*')
      BEGIN SELECT RAISE(ABORT,'Account numbers must contain exactly 10 digits'); END;
      CREATE TRIGGER IF NOT EXISTS accounts_account_number_format_update BEFORE UPDATE OF account_number ON accounts
      WHEN NEW.account_number IS NOT NULL AND (length(NEW.account_number)<>10 OR NEW.account_number GLOB '*[^0-9]*')
      BEGIN SELECT RAISE(ABORT,'Account numbers must contain exactly 10 digits'); END;
      CREATE TRIGGER IF NOT EXISTS accounts_account_number_immutable BEFORE UPDATE OF account_number, masked_number ON accounts
      WHEN OLD.account_number IS NOT NULL AND (NEW.account_number IS NOT OLD.account_number OR NEW.masked_number<>substr(OLD.account_number,-4))
      BEGIN SELECT RAISE(ABORT,'Account numbers cannot be changed once assigned'); END;
      CREATE TRIGGER IF NOT EXISTS accounts_holder_name_after_insert AFTER INSERT ON accounts
      BEGIN UPDATE accounts SET name=(SELECT trim(first_name||' '||last_name) FROM users WHERE id=NEW.user_id) WHERE id=NEW.id; END;
      CREATE TRIGGER IF NOT EXISTS accounts_holder_name_immutable BEFORE UPDATE OF name ON accounts
      WHEN NEW.name<>(SELECT trim(first_name||' '||last_name) FROM users WHERE id=NEW.user_id)
      BEGIN SELECT RAISE(ABORT,'Account name must match the account holder'); END;
      CREATE TRIGGER IF NOT EXISTS accounts_holder_name_after_user_update AFTER UPDATE OF first_name,last_name ON users
      BEGIN UPDATE accounts SET name=trim(NEW.first_name||' '||NEW.last_name) WHERE user_id=NEW.id; END;
    `);
    this.db.exec("UPDATE accounts SET name=(SELECT trim(first_name||' '||last_name) FROM users WHERE users.id=accounts.user_id)");
  }

  private ensureLegacyCredentials(){const rows=this.db.prepare("SELECT u.id FROM users u LEFT JOIN local_credentials c ON c.user_id=u.id WHERE c.user_id IS NULL").all() as Array<{id:string}>;const insert=this.db.prepare("INSERT INTO local_credentials (user_id,password_hash,password_salt,updated_at) VALUES (?,?,?,?)");this.db.transaction(()=>{for(const row of rows){const credential=createPasswordHash(process.env.CLIPX_DEFAULT_PASSWORD||"ClipXLocal123");insert.run(row.id,credential.hash,credential.salt,new Date().toISOString());}})();}
  async ping(){this.db.prepare("SELECT 1").get();}
  async getUser(id:string):Promise<User|undefined>{const row=this.db.prepare("SELECT * FROM users WHERE id=?").get(id) as UserRow|undefined;return row?{id:row.id,email:row.email,firstName:row.first_name,lastName:row.last_name,profileImageUrl:row.profile_image_url,isAdmin:Boolean(row.is_admin),isActive:Boolean(row.is_active),createdAt:row.created_at,updatedAt:row.updated_at}:undefined;}
  async getUserAvatar(userId:string):Promise<AvatarFile|undefined>{const row=this.db.prepare("SELECT content_type,image_data,updated_at FROM user_avatars WHERE user_id=?").get(userId) as AvatarRow|undefined;return row?{contentType:row.content_type,data:Buffer.from(row.image_data),updatedAt:row.updated_at}:undefined;}
  async updateUserAvatar(userId:string,avatar:AvatarUpload):Promise<User>{const now=new Date().toISOString(),profileImageUrl=`/api/avatars/${userId}?v=${Date.now()}`;this.db.transaction(()=>{const result=this.db.prepare("UPDATE users SET profile_image_url=?,updated_at=? WHERE id=?").run(profileImageUrl,now,userId);if(!result.changes)throw Object.assign(new Error("Account not found"),{status:404});this.db.prepare("INSERT INTO user_avatars (user_id,content_type,image_data,byte_size,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET content_type=excluded.content_type,image_data=excluded.image_data,byte_size=excluded.byte_size,updated_at=excluded.updated_at").run(userId,avatar.contentType,avatar.data,avatar.data.byteLength,now);})();const user=await this.getUser(userId);if(!user)throw Object.assign(new Error("Account not found"),{status:404});return user;}
  private getLocalUser(email:string){const row=this.db.prepare("SELECT id,email,first_name,last_name,is_admin FROM users WHERE lower(email)=lower(?)").get(email) as Pick<UserRow,"id"|"email"|"first_name"|"last_name"|"is_admin">|undefined;return row?{id:row.id,email:row.email,firstName:row.first_name,lastName:row.last_name,isAdmin:Boolean(row.is_admin)}:undefined;}
  async createLocalUser(email:string,password:string,firstName:string,lastName:string){if(this.getLocalUser(email))throw Object.assign(new Error("An account with this email already exists"),{status:409});const id=randomUUID(),normalized=email.toLowerCase(),normalizedFirstName=firstName.trim(),normalizedLastName=lastName.trim(),now=new Date().toISOString(),credential=createPasswordHash(password);this.db.transaction(()=>{this.db.prepare("INSERT INTO users (id,email,first_name,last_name,is_admin,is_active,created_at,updated_at,last_active_at) VALUES (?,?,?,?,0,1,?,?,?)").run(id,normalized,normalizedFirstName,normalizedLastName,now,now,now);this.db.prepare("INSERT INTO user_preferences (user_id) VALUES (?)").run(id);this.db.prepare("INSERT INTO local_credentials (user_id,password_hash,password_salt,updated_at) VALUES (?,?,?,?)").run(id,credential.hash,credential.salt,now);})();return{id,email:normalized,firstName:normalizedFirstName,lastName:normalizedLastName,isAdmin:false};}
  async authenticateLocalUser(email:string,password:string){const row=this.db.prepare("SELECT u.id,u.email,u.first_name,u.last_name,u.is_admin,u.is_active,c.password_hash,c.password_salt FROM users u JOIN local_credentials c ON c.user_id=u.id WHERE lower(u.email)=lower(?)").get(email) as {id:string;email:string;first_name:string;last_name:string;is_admin:number;is_active:number;password_hash:string;password_salt:string}|undefined;if(!row||!row.is_active||!passwordMatches(password,row.password_salt,row.password_hash))return undefined;this.db.prepare("UPDATE users SET last_active_at=? WHERE id=?").run(new Date().toISOString(),row.id);return{id:row.id,email:row.email,firstName:row.first_name,lastName:row.last_name,isAdmin:Boolean(row.is_admin)};}
  async createSession(userId:string,tokenHash:string,expiresAt:Date){const now=new Date().toISOString();this.db.transaction(()=>{this.db.prepare("DELETE FROM sessions WHERE expires_at<=?").run(now);this.db.prepare("INSERT INTO sessions (token_hash,user_id,expires_at,created_at) VALUES (?,?,?,?)").run(tokenHash,userId,expiresAt.toISOString(),now);})();}
  async getSessionUser(tokenHash:string):Promise<LocalAuthUser|undefined>{const row=this.db.prepare("SELECT u.id,u.email,u.first_name,u.last_name,u.is_admin FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.is_active=1").get(tokenHash,new Date().toISOString()) as Pick<UserRow,"id"|"email"|"first_name"|"last_name"|"is_admin">|undefined;return row?{id:row.id,email:row.email,firstName:row.first_name,lastName:row.last_name,isAdmin:Boolean(row.is_admin)}:undefined;}
  async deleteSession(tokenHash:string){this.db.prepare("DELETE FROM sessions WHERE token_hash=?").run(tokenHash);}
  async deleteUserSessions(userId:string){this.db.prepare("DELETE FROM sessions WHERE user_id=?").run(userId);}
  async recordSecurityEvent(eventType:string,userId?:string,resourceId?:string,ipAddress?:string){this.db.prepare("INSERT INTO security_audit_events (id,user_id,event_type,resource_id,ip_address,created_at) VALUES (?,?,?,?,?,?)").run(randomUUID(),userId??null,eventType,resourceId??null,ipAddress??null,new Date().toISOString());}
  async getAccounts(userId:string){return(this.db.prepare("SELECT id,name,type,account_number,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps FROM accounts WHERE user_id=? ORDER BY type,id").all(userId) as AccountRow[]).map(toAccount);}
  async getTransactions(userId:string){return(this.db.prepare("SELECT t.* FROM transactions t JOIN accounts a ON a.id=t.account_id WHERE a.user_id=? ORDER BY t.created_at DESC").all(userId) as TransactionRow[]).map(toTransaction);}
  async getTransaction(userId:string,transactionId:string):Promise<TransactionDetails>{const row=this.db.prepare("SELECT t.*,a.name account_name,a.type account_type,a.masked_number account_masked_number FROM transactions t JOIN accounts a ON a.id=t.account_id WHERE t.id=? AND a.user_id=?").get(transactionId,userId) as TransactionDetailsRow|undefined;if(!row)throw Object.assign(new Error("Transaction not found"),{status:404});return toTransactionDetails(row);}
  async getCards(userId:string){return(this.db.prepare("SELECT c.* FROM cards c JOIN accounts a ON a.id=c.account_id WHERE a.user_id=? ORDER BY c.type").all(userId) as CardRow[]).map(toCard);}
  async getCardDetails(userId:string,cardId:string):Promise<CardDetails>{const row=this.db.prepare("SELECT c.* FROM cards c JOIN accounts a ON a.id=c.account_id WHERE c.id=? AND a.user_id=?").get(cardId,userId) as CardRow|undefined;if(!row)throw Object.assign(new Error("Card not found"),{status:404});if(!row.pan_ciphertext||!row.pan_iv||!row.pan_auth_tag)throw Object.assign(new Error("Secure details are unavailable for this legacy card"),{status:409});return{cardId:row.id,number:decryptPan({ciphertext:row.pan_ciphertext,iv:row.pan_iv,authTag:row.pan_auth_tag},requireCardDataKey()),securityCode:generateSecurityCode(),expires:row.expires,revealExpiresAt:new Date(Date.now()+30_000).toISOString()};}
  async getNotifications(userId:string){return(this.db.prepare("SELECT id,type,title,message,resource_id,is_read,created_at FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 20").all(userId) as NotificationRow[]).map(toNotification);}
  async markNotificationRead(userId:string,notificationId:string):Promise<AppNotification>{this.db.prepare("UPDATE notifications SET is_read=1 WHERE id=? AND user_id=?").run(notificationId,userId);const row=this.db.prepare("SELECT id,type,title,message,resource_id,is_read,created_at FROM notifications WHERE id=? AND user_id=?").get(notificationId,userId) as NotificationRow|undefined;if(!row)throw Object.assign(new Error("Notification not found"),{status:404});return toNotification(row);}
  async markAllNotificationsRead(userId:string){this.db.prepare("UPDATE notifications SET is_read=1 WHERE user_id=? AND is_read=0").run(userId);}
  async getSupportMessages(customerUserId:string,viewerRole:SupportSenderRole){const rows=this.db.prepare("SELECT m.*,trim(u.first_name||' '||u.last_name) sender_name FROM support_messages m JOIN users u ON u.id=m.sender_user_id WHERE m.customer_user_id=? ORDER BY m.created_at,m.id LIMIT 500").all(customerUserId) as SupportMessageRow[];return rows.map((row)=>toSupportMessage(row,viewerRole));}
  async createSupportMessage(customerUserId:string,senderUserId:string,senderRole:SupportSenderRole,body:string){const row=this.db.transaction(()=>{const customer=this.db.prepare("SELECT id FROM users WHERE id=?").get(customerUserId) as {id:string}|undefined;const sender=this.db.prepare("SELECT id,trim(first_name||' '||last_name) sender_name,is_admin FROM users WHERE id=?").get(senderUserId) as {id:string;sender_name:string;is_admin:number}|undefined;if(!customer)throw Object.assign(new Error("Customer not found"),{status:404});if(!sender)throw Object.assign(new Error("Message sender not found"),{status:404});if(senderRole==="customer"&&senderUserId!==customerUserId)throw Object.assign(new Error("Customers can only message from their own account"),{status:403});if(senderRole==="admin"&&!Number(sender.is_admin))throw Object.assign(new Error("Administrator access required"),{status:403});const id=randomUUID(),createdAt=new Date().toISOString();this.db.prepare("INSERT INTO support_messages (id,customer_user_id,sender_user_id,sender_role,body,read_by_customer,read_by_admin,created_at) VALUES (?,?,?,?,?,?,?,?)").run(id,customerUserId,senderUserId,senderRole,body,Number(senderRole==="customer"),Number(senderRole==="admin"),createdAt);const notification=this.db.prepare("INSERT INTO notifications (id,user_id,type,title,message,resource_id,created_at) VALUES (?,?,?, ?,?,?,?)");if(senderRole==="customer"){const admins=this.db.prepare("SELECT id FROM users WHERE is_admin=1 AND is_active=1 AND id<>?").all(senderUserId) as Array<{id:string}>;for(const admin of admins)notification.run(randomUUID(),admin.id,"support_message","New support message",`${sender.sender_name} sent you a new support message.`,customerUserId,createdAt);}else notification.run(randomUUID(),customerUserId,"support_message","Support replied",`${sender.sender_name} replied to your support conversation.`,customerUserId,createdAt);return this.db.prepare("SELECT m.*,trim(u.first_name||' '||u.last_name) sender_name FROM support_messages m JOIN users u ON u.id=m.sender_user_id WHERE m.id=?").get(id) as SupportMessageRow;})();return toSupportMessage(row,senderRole);}
  async markSupportMessagesRead(customerUserId:string,viewerRole:SupportSenderRole){const column=viewerRole==="customer"?"read_by_customer":"read_by_admin";this.db.prepare(`UPDATE support_messages SET ${column}=1 WHERE customer_user_id=? AND ${column}=0`).run(customerUserId);}
  async getBeneficiaries(userId:string){return(this.db.prepare("SELECT id,name,bank_name,masked_account,initials FROM beneficiaries WHERE user_id=? ORDER BY name").all(userId) as BeneficiaryRow[]).map((row)=>({id:row.id,name:row.name,bankName:row.bank_name,maskedAccount:row.masked_account,initials:row.initials}));}
  async getOverview(userId:string):Promise<BankingOverview>{const accounts=await this.getAccounts(userId);const flow=this.db.prepare("SELECT month,income_cents,spending_cents FROM cash_flow WHERE user_id=? ORDER BY sort_order").all(userId) as Array<{month:string;income_cents:number;spending_cents:number}>;const latest=flow.at(-1);return{totalBalance:accounts.reduce((sum,a)=>sum+a.balance,0),availableBalance:accounts.reduce((sum,a)=>sum+a.availableBalance,0),monthlyIncome:dollars(latest?.income_cents??0),monthlySpending:dollars(latest?.spending_cents??0),accounts,cashFlow:flow.map((row)=>({month:row.month,income:dollars(row.income_cents),spending:dollars(row.spending_cents)}))};}
  async createTransfer(userId:string,transfer:CreateTransfer){return this.db.transaction(()=>{const account=this.db.prepare("SELECT * FROM accounts WHERE id=? AND user_id=?").get(transfer.sourceAccountId,userId) as AccountRow|undefined;const beneficiary=this.db.prepare("SELECT * FROM beneficiaries WHERE id=? AND user_id=?").get(transfer.beneficiaryId,userId) as BeneficiaryRow|undefined;if(!account)throw Object.assign(new Error("Source account not found"),{status:404});if(!beneficiary)throw Object.assign(new Error("Recipient not found"),{status:404});const amount=cents(transfer.amount);if(account.available_balance_cents<amount)throw Object.assign(new Error("Insufficient available balance"),{status:422});this.db.prepare("UPDATE accounts SET balance_cents=balance_cents-?,available_balance_cents=available_balance_cents-? WHERE id=?").run(amount,amount,account.id);const row:TransactionRow={id:randomUUID(),account_id:account.id,description:transfer.note||"Bank transfer",merchant:beneficiary.name,category:"transfer",amount_cents:amount,direction:"debit",status:"completed",reference:`TRF-${randomBytes(5).toString("hex").toUpperCase()}`,created_at:new Date().toISOString()};this.db.prepare("INSERT INTO transactions (id,account_id,description,merchant,category,amount_cents,direction,status,reference,created_at) VALUES (@id,@account_id,@description,@merchant,@category,@amount_cents,@direction,@status,@reference,@created_at)").run(row);return toTransaction(row);})();}
  async createInternalTransfer(userId:string,transfer:CreateInternalTransfer):Promise<InternalTransferReceipt>{const perform=this.db.transaction(()=>{if(transfer.sourceAccountId===transfer.destinationAccountId)throw Object.assign(new Error("Choose two different accounts"),{status:400});const source=this.db.prepare("SELECT * FROM accounts WHERE id=? AND user_id=?").get(transfer.sourceAccountId,userId) as AccountRow|undefined;const destination=this.db.prepare("SELECT * FROM accounts WHERE id=? AND user_id=?").get(transfer.destinationAccountId,userId) as AccountRow|undefined;if(!source)throw Object.assign(new Error("Source account not found"),{status:404});if(!destination)throw Object.assign(new Error("Destination account not found"),{status:404});const amountCents=cents(transfer.amount);if(source.available_balance_cents<amountCents)throw Object.assign(new Error("Insufficient available balance"),{status:422});const id=randomUUID(),reference=`INT-${randomBytes(8).toString("hex").toUpperCase()}`,createdAt=new Date().toISOString();this.db.prepare("UPDATE accounts SET balance_cents=balance_cents-?,available_balance_cents=available_balance_cents-? WHERE id=?").run(amountCents,amountCents,source.id);this.db.prepare("UPDATE accounts SET balance_cents=balance_cents+?,available_balance_cents=available_balance_cents+? WHERE id=?").run(amountCents,amountCents,destination.id);this.db.prepare("INSERT INTO internal_transfers (id,user_id,source_account_id,destination_account_id,amount_cents,note,reference,status,created_at) VALUES (?,?,?,?,?,?,?,'completed',?)").run(id,userId,source.id,destination.id,amountCents,transfer.note,reference,createdAt);const insertLedger=this.db.prepare("INSERT INTO transactions (id,account_id,internal_transfer_id,description,merchant,category,amount_cents,direction,status,reference,created_at) VALUES (?,?,?,?,?,'transfer',?,?,'completed',?,?)");insertLedger.run(randomUUID(),source.id,id,transfer.note,`To ${destination.name}`,amountCents,"debit",`${reference}-OUT`,createdAt);insertLedger.run(randomUUID(),destination.id,id,transfer.note,`From ${source.name}`,amountCents,"credit",`${reference}-IN`,createdAt);return{id,sourceAccountId:source.id,sourceAccountName:source.name,destinationAccountId:destination.id,destinationAccountName:destination.name,amount:dollars(amountCents),note:transfer.note,reference,createdAt};});return perform.immediate();}
  async lookupPeerRecipient(userId:string,accountNumber:string):Promise<PeerRecipient>{const recipient=this.db.prepare("SELECT a.*,u.first_name,u.last_name FROM accounts a JOIN users u ON u.id=a.user_id WHERE a.account_number=? AND u.is_active=1").get(accountNumber) as PeerRecipientRow|undefined;if(!recipient)throw Object.assign(new Error("Recipient account not found"),{status:404});if(recipient.user_id===userId)throw Object.assign(new Error("Use Between my accounts to transfer to your own account"),{status:422});return{accountNumber,accountName:recipient.name,recipientName:`${recipient.first_name} ${recipient.last_name}`.trim()};}
  async createPeerTransfer(userId:string,transfer:CreatePeerTransfer):Promise<PeerTransferReceipt>{const perform=this.db.transaction(()=>{const source=this.db.prepare("SELECT * FROM accounts WHERE id=? AND user_id=?").get(transfer.sourceAccountId,userId) as AccountRow|undefined;const recipient=this.db.prepare("SELECT a.*,u.first_name,u.last_name FROM accounts a JOIN users u ON u.id=a.user_id WHERE a.account_number=? AND u.is_active=1").get(transfer.recipientAccountNumber) as PeerRecipientRow|undefined;if(!source)throw Object.assign(new Error("Source account not found"),{status:404});if(!recipient)throw Object.assign(new Error("Recipient account not found"),{status:404});if(recipient.user_id===userId)throw Object.assign(new Error("Use Between my accounts to transfer to your own account"),{status:422});const amountCents=cents(transfer.amount);if(source.available_balance_cents<amountCents)throw Object.assign(new Error("Insufficient available balance"),{status:422});const id=randomUUID(),reference=`P2P-${randomBytes(8).toString("hex").toUpperCase()}`,createdAt=new Date().toISOString(),recipientName=`${recipient.first_name} ${recipient.last_name}`.trim();this.db.prepare("UPDATE accounts SET balance_cents=balance_cents-?,available_balance_cents=available_balance_cents-? WHERE id=?").run(amountCents,amountCents,source.id);this.db.prepare("UPDATE accounts SET balance_cents=balance_cents+?,available_balance_cents=available_balance_cents+? WHERE id=?").run(amountCents,amountCents,recipient.id);this.db.prepare("INSERT INTO peer_transfers (id,sender_user_id,source_account_id,recipient_user_id,destination_account_id,amount_cents,note,reference,status,created_at) VALUES (?,?,?,?,?,?,?,?,'completed',?)").run(id,userId,source.id,recipient.user_id,recipient.id,amountCents,transfer.note,reference,createdAt);const insertLedger=this.db.prepare("INSERT INTO transactions (id,account_id,peer_transfer_id,description,merchant,category,amount_cents,direction,status,reference,created_at) VALUES (?,?,?,?,?,'transfer',?,?,'completed',?,?)");insertLedger.run(randomUUID(),source.id,id,transfer.note,recipientName,amountCents,"debit",`${reference}-OUT`,createdAt);insertLedger.run(randomUUID(),recipient.id,id,transfer.note,`From ${source.name}`,amountCents,"credit",`${reference}-IN`,createdAt);return{id,sourceAccountId:source.id,sourceAccountName:source.name,recipientAccountNumber:transfer.recipientAccountNumber,destinationAccountName:recipient.name,recipientName,amount:dollars(amountCents),note:transfer.note,reference,createdAt};});return perform.immediate();}
  async updateCard(userId:string,cardId:string,update:UpdateCard){const row=this.db.prepare("SELECT c.* FROM cards c JOIN accounts a ON a.id=c.account_id WHERE c.id=? AND a.user_id=?").get(cardId,userId) as CardRow|undefined;if(!row)throw Object.assign(new Error("Card not found"),{status:404});this.db.prepare("UPDATE cards SET status=?,spending_limit_cents=? WHERE id=?").run(update.status??row.status,update.spendingLimit===undefined?row.spending_limit_cents:cents(update.spendingLimit),cardId);return toCard(this.db.prepare("SELECT * FROM cards WHERE id=?").get(cardId) as CardRow);}
  async getSettings(userId:string):Promise<AccountSettings>{const row=this.db.prepare("SELECT u.email,u.first_name,u.last_name,u.profile_image_url,p.transaction_alerts,p.monthly_summary,p.show_balances FROM users u JOIN user_preferences p ON p.user_id=u.id WHERE u.id=?").get(userId) as {email:string;first_name:string;last_name:string;profile_image_url:string|null;transaction_alerts:number;monthly_summary:number;show_balances:number}|undefined;if(!row)throw Object.assign(new Error("Account settings not found"),{status:404});return{profile:{firstName:row.first_name,lastName:row.last_name,email:row.email,profileImageUrl:row.profile_image_url},preferences:{transactionAlerts:Boolean(row.transaction_alerts),monthlySummary:Boolean(row.monthly_summary),showBalances:Boolean(row.show_balances)}};}
  async updateProfile(userId:string,update:UpdateProfile){const holderName=accountHolderName(update.firstName,update.lastName);this.db.transaction(()=>{const result=this.db.prepare("UPDATE users SET first_name=?,last_name=?,updated_at=? WHERE id=?").run(update.firstName,update.lastName,new Date().toISOString(),userId);if(!result.changes)throw Object.assign(new Error("Account not found"),{status:404});this.db.prepare("UPDATE accounts SET name=? WHERE user_id=?").run(holderName,userId);this.db.prepare("UPDATE cards SET holder_name=? WHERE account_id IN (SELECT id FROM accounts WHERE user_id=?)").run(holderName.toUpperCase(),userId);})();return this.getSettings(userId);}
  async updatePreferences(userId:string,update:UpdatePreferences){const current=(await this.getSettings(userId)).preferences;this.db.prepare("UPDATE user_preferences SET transaction_alerts=?,monthly_summary=?,show_balances=? WHERE user_id=?").run(Number(update.transactionAlerts??current.transactionAlerts),Number(update.monthlySummary??current.monthlySummary),Number(update.showBalances??current.showBalances),userId);return this.getSettings(userId);}
  async changePassword(userId:string,update:ChangePassword){const row=this.db.prepare("SELECT password_hash,password_salt FROM local_credentials WHERE user_id=?").get(userId) as {password_hash:string;password_salt:string}|undefined;if(!row||!passwordMatches(update.currentPassword,row.password_salt,row.password_hash))throw Object.assign(new Error("Current password is incorrect"),{status:401});const credential=createPasswordHash(update.newPassword);this.db.prepare("UPDATE local_credentials SET password_hash=?,password_salt=?,updated_at=? WHERE user_id=?").run(credential.hash,credential.salt,new Date().toISOString(),userId);}
  async getAdminStats():Promise<AdminStats>{const counts=this.db.prepare("SELECT COUNT(*) total,COALESCE(SUM(CASE WHEN is_active=1 THEN 1 ELSE 0 END),0) active FROM users WHERE is_admin=0").get() as {total:number;active:number};const balance=this.db.prepare("SELECT COALESCE(SUM(balance_cents),0) value FROM accounts").get() as {value:number};const externalVolume=this.db.prepare("SELECT COALESCE(SUM(amount_cents),0) value FROM transactions WHERE status='completed' AND internal_transfer_id IS NULL AND peer_transfer_id IS NULL").get() as {value:number};const internalVolume=this.db.prepare("SELECT COALESCE(SUM(amount_cents),0) value FROM internal_transfers WHERE status='completed'").get() as {value:number};const peerVolume=this.db.prepare("SELECT COALESCE(SUM(amount_cents),0) value FROM peer_transfers WHERE status='completed'").get() as {value:number};const pending=this.db.prepare("SELECT COUNT(*) value FROM transactions WHERE status='pending'").get() as {value:number};return{totalCustomers:counts.total,activeCustomers:counts.active,managedBalance:dollars(balance.value),processedVolume:dollars(externalVolume.value+internalVolume.value+peerVolume.value),pendingTransactions:pending.value,systemStatus:"operational"};}
  async getAdminUsers():Promise<AdminCustomer[]>{const rows=this.db.prepare("SELECT u.*,COALESCE(SUM(a.balance_cents),0) balance_cents FROM users u LEFT JOIN accounts a ON a.user_id=u.id GROUP BY u.id ORDER BY u.last_active_at DESC").all() as Array<UserRow&{balance_cents:number}>;return rows.map((row)=>({id:row.id,email:row.email,firstName:row.first_name,lastName:row.last_name,initials:`${row.first_name[0]??""}${row.last_name[0]??""}`||"CX",profileImageUrl:row.profile_image_url,isAdmin:Boolean(row.is_admin),isActive:Boolean(row.is_active),balance:dollars(row.balance_cents),createdAt:row.created_at,lastActiveAt:row.last_active_at}));}
  async createAdminUser(input:CreateAdminCustomer){if(this.db.prepare("SELECT 1 FROM users WHERE lower(email)=lower(?)").get(input.email))throw Object.assign(new Error("Another account already uses this email"),{status:409});const userId=randomUUID(),now=new Date().toISOString(),credential=createPasswordHash(input.password),holderName=accountHolderName(input.firstName,input.lastName);this.db.transaction(()=>{this.db.prepare("INSERT INTO users (id,email,first_name,last_name,is_admin,is_active,created_at,updated_at,last_active_at) VALUES (?,?,?,?,?,?,?,?,?)").run(userId,input.email.toLowerCase(),input.firstName,input.lastName,Number(input.isAdmin),Number(input.isActive),now,now,now);this.db.prepare("INSERT INTO user_preferences (user_id) VALUES (?)").run(userId);this.db.prepare("INSERT INTO local_credentials (user_id,password_hash,password_salt,updated_at) VALUES (?,?,?,?)").run(userId,credential.hash,credential.salt,now);if(input.account){const balance=cents(input.account.openingBalance);this.db.prepare("INSERT INTO accounts (id,user_id,name,type,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps) VALUES (?,?,?,?,?,'USD',?,?,NULL)").run(randomUUID(),userId,holderName,input.account.type,input.account.maskedNumber,balance,balance);}})();const customer=(await this.getAdminUsers()).find((item)=>item.id===userId);if(!customer)throw Object.assign(new Error("Customer could not be created"),{status:500});return customer;}
  async getAdminUserDetails(userId:string):Promise<AdminCustomerDetails>{const customer=(await this.getAdminUsers()).find((item)=>item.id===userId);if(!customer)throw Object.assign(new Error("Customer not found"),{status:404});const settings=await this.getSettings(userId);return{customer,accounts:await this.getAccounts(userId),cards:await this.getCards(userId),transactions:(await this.getAdminTransactions()).filter((item)=>item.customerId===userId),preferences:settings.preferences};}
  async updateAdminUser(userId:string,update:UpdateAdminUser){const row=this.db.prepare("SELECT email,first_name,last_name,is_admin,is_active FROM users WHERE id=?").get(userId) as {email:string;first_name:string;last_name:string;is_admin:number;is_active:number}|undefined;if(!row)throw Object.assign(new Error("Customer not found"),{status:404});const email=(update.email??row.email).toLowerCase();if(this.db.prepare("SELECT 1 FROM users WHERE lower(email)=lower(?) AND id<>?").get(email,userId))throw Object.assign(new Error("Another account already uses this email"),{status:409});const wasActive=Boolean(row.is_active),isActive=update.isActive??wasActive,firstName=update.firstName??row.first_name,lastName=update.lastName??row.last_name,holderName=accountHolderName(firstName,lastName);this.db.transaction(()=>{this.db.prepare("UPDATE users SET email=?,first_name=?,last_name=?,is_admin=?,is_active=?,updated_at=? WHERE id=?").run(email,firstName,lastName,Number(update.isAdmin??Boolean(row.is_admin)),Number(isActive),new Date().toISOString(),userId);this.db.prepare("UPDATE accounts SET name=? WHERE user_id=?").run(holderName,userId);this.db.prepare("UPDATE cards SET holder_name=? WHERE account_id IN (SELECT id FROM accounts WHERE user_id=?)").run(holderName.toUpperCase(),userId);if(!wasActive||!isActive)this.db.prepare("DELETE FROM sessions WHERE user_id=?").run(userId);})();const customer=(await this.getAdminUsers()).find((item)=>item.id===userId);if(!customer)throw Object.assign(new Error("Customer not found"),{status:404});return customer;}
  async createAdminAccount(userId:string,input:CreateAdminAccount){const owner=this.db.prepare("SELECT first_name,last_name FROM users WHERE id=?").get(userId) as {first_name:string;last_name:string}|undefined;if(!owner)throw Object.assign(new Error("Customer not found"),{status:404});const balance=cents(input.openingBalance),accountId=randomUUID();this.db.prepare("INSERT INTO accounts (id,user_id,name,type,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps) VALUES (?,?,?,?,?,'USD',?,?,NULL)").run(accountId,userId,accountHolderName(owner.first_name,owner.last_name),input.type,input.maskedNumber,balance,balance);return toAccount(this.db.prepare("SELECT id,name,type,account_number,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps FROM accounts WHERE id=?").get(accountId) as AccountRow);}
  async updateAdminAccount(userId:string,accountId:string,update:UpdateAdminAccount){const row=this.db.prepare("SELECT id,name,type,account_number,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps FROM accounts WHERE id=? AND user_id=?").get(accountId,userId) as AccountRow|undefined;if(!row)throw Object.assign(new Error("Customer account not found"),{status:404});if(row.account_number&&update.maskedNumber!==undefined&&update.maskedNumber!==row.masked_number)throw Object.assign(new Error("The final four digits are locked after an account number is assigned"),{status:409});this.db.prepare("UPDATE accounts SET type=?,masked_number=? WHERE id=? AND user_id=?").run(update.type??row.type,update.maskedNumber??row.masked_number,accountId,userId);return toAccount(this.db.prepare("SELECT id,name,type,account_number,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps FROM accounts WHERE id=?").get(accountId) as AccountRow);}
  async assignAdminAccountNumber(userId:string,accountId:string){const existing=this.db.prepare("SELECT id,name,type,account_number,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps FROM accounts WHERE id=? AND user_id=?").get(accountId,userId) as AccountRow|undefined;if(!existing)throw Object.assign(new Error("Customer account not found"),{status:404});if(existing.account_number)throw Object.assign(new Error("An account number has already been assigned and cannot be changed"),{status:409});for(let attempt=0;attempt<5;attempt+=1){try{const number=generateAccountNumber();const result=this.db.prepare("UPDATE accounts SET account_number=?,masked_number=? WHERE id=? AND user_id=? AND account_number IS NULL").run(number,number.slice(-4),accountId,userId);if(!result.changes)throw Object.assign(new Error("An account number has already been assigned and cannot be changed"),{status:409});return toAccount(this.db.prepare("SELECT id,name,type,account_number,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps FROM accounts WHERE id=?").get(accountId) as AccountRow);}catch(error){if(error&&typeof error==="object"&&"code" in error&&error.code==="SQLITE_CONSTRAINT_UNIQUE")continue;throw error;}}throw Object.assign(new Error("A unique account number could not be allocated. Try again."),{status:503});}
  async createAdminCard(userId:string,input:AdminCardInput):Promise<BankCard>{const perform=this.db.transaction(()=>{const owner=this.db.prepare("SELECT a.id account_id,upper(trim(u.first_name||' '||u.last_name)) holder_name FROM accounts a JOIN users u ON u.id=a.user_id WHERE a.id=? AND a.user_id=?").get(input.accountId,userId) as {account_id:string;holder_name:string}|undefined;if(!owner)throw Object.assign(new Error("Customer account not found"),{status:404});const network=input.network??"Mastercard",key=requireCardDataKey(),id=randomUUID(),pan=network==="Visa"?generateVisaPan():generateMastercardPan(),expires=generateExpiry(),encrypted=encryptPan(pan,key),now=new Date().toISOString();this.db.prepare("INSERT INTO cards (id,account_id,holder_name,last_four,network,type,status,spending_limit_cents,expires,pan_ciphertext,pan_iv,pan_auth_tag,pan_fingerprint,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,owner.account_id,owner.holder_name,pan.slice(-4),network,input.type,input.status,cents(input.spendingLimit),expires,encrypted.ciphertext,encrypted.iv,encrypted.authTag,fingerprintPan(pan,key),now);this.db.prepare("INSERT INTO notifications (id,user_id,type,title,message,resource_id,is_read,created_at) VALUES (?,?,'card_issued','Your new card is ready',?,?,0,?)").run(randomUUID(),userId,`${input.type[0]?.toUpperCase()}${input.type.slice(1)} ${network} ending in ${pan.slice(-4)} was added to your account.`,id,now);return toCard(this.db.prepare("SELECT * FROM cards WHERE id=?").get(id) as CardRow);});return perform.immediate();}
  async revokeAdminCard(userId:string,cardId:string):Promise<BankCard>{const row=this.db.prepare("SELECT c.* FROM cards c JOIN accounts a ON a.id=c.account_id WHERE c.id=? AND a.user_id=?").get(cardId,userId) as CardRow|undefined;if(!row)throw Object.assign(new Error("Card not found"),{status:404});this.db.prepare("UPDATE cards SET status='frozen' WHERE id=?").run(cardId);return toCard(this.db.prepare("SELECT * FROM cards WHERE id=?").get(cardId) as CardRow);}
  async deleteAdminCard(userId:string,cardId:string):Promise<void>{const perform=this.db.transaction(()=>{const row=this.db.prepare("SELECT c.id FROM cards c JOIN accounts a ON a.id=c.account_id WHERE c.id=? AND a.user_id=?").get(cardId,userId) as {id:string}|undefined;if(!row)throw Object.assign(new Error("Card not found"),{status:404});this.db.prepare("DELETE FROM notifications WHERE user_id=? AND type='card_issued' AND resource_id=?").run(userId,cardId);this.db.prepare("DELETE FROM cards WHERE id=?").run(cardId);});perform.immediate();}
  async getAdminTransactions():Promise<AdminTransaction[]>{const rows=this.db.prepare("SELECT t.*,u.id customer_id,trim(u.first_name||' '||u.last_name) customer_name FROM transactions t JOIN accounts a ON a.id=t.account_id JOIN users u ON u.id=a.user_id ORDER BY t.created_at DESC").all() as Array<TransactionRow&{customer_id:string;customer_name:string}>;return rows.map((row)=>({...toTransaction(row),customerId:row.customer_id,customerName:row.customer_name,risk:row.amount_cents>=cents(2500)||row.status==="failed"?"review":"standard"}));}
  async getAdminTransaction(transactionId:string):Promise<AdminTransactionDetails>{const row=this.db.prepare("SELECT t.*,a.name account_name,a.type account_type,a.masked_number account_masked_number,trim(u.first_name||' '||u.last_name) customer_name FROM transactions t JOIN accounts a ON a.id=t.account_id JOIN users u ON u.id=a.user_id WHERE t.id=?").get(transactionId) as (TransactionDetailsRow&{customer_name:string})|undefined;if(!row)throw Object.assign(new Error("Transaction not found"),{status:404});return{...toTransactionDetails(row),customerName:row.customer_name,risk:row.amount_cents>=cents(2500)||row.status==="failed"?"review":"standard"};}
}
