import { randomBytes,randomInt,randomUUID,scryptSync,timingSafeEqual } from "node:crypto";
import path from "node:path";
import Database from "better-sqlite3";
import type { User } from "@clipx/contracts/schema";
import type { Account,BankCard,BankingOverview,BankTransaction,Beneficiary,CreateTransfer,UpdateCard } from "@clipx/contracts/banking";
import type { AdminCustomer,AdminCustomerDetails,AdminStats,AdminTransaction,CreateAdminAccount,CreateAdminCustomer,UpdateAdminAccount,UpdateAdminUser } from "@clipx/contracts/admin";
import type { AccountSettings,ChangePassword,UpdatePreferences,UpdateProfile } from "@clipx/contracts/settings";
import type { LocalAuthUser } from "@clipx/contracts/auth";
import type { IStorage } from "./storage.js";

type UserRow={id:string;email:string;first_name:string;last_name:string;profile_image_url:string|null;is_admin:number;is_active:number;created_at:string;updated_at:string;last_active_at:string};
type AccountRow={id:string;name:string;type:"checking"|"savings";account_number:string|null;masked_number:string;currency:"USD";balance_cents:number;available_balance_cents:number;interest_rate_bps:number|null};
type TransactionRow={id:string;account_id:string;description:string;merchant:string;category:BankTransaction["category"];amount_cents:number;direction:BankTransaction["direction"];status:BankTransaction["status"];reference:string;created_at:string};
type CardRow={id:string;account_id:string;holder_name:string;last_four:string;network:"Visa";type:BankCard["type"];status:BankCard["status"];spending_limit_cents:number;expires:string};
type BeneficiaryRow={id:string;name:string;bank_name:string;masked_account:string;initials:string};

const cents=(value:number)=>Math.round(value*100);
const dollars=(value:number)=>value/100;
const createPasswordHash=(password:string,salt=randomBytes(16).toString("hex"))=>({salt,hash:scryptSync(password,salt,64).toString("hex")});
const passwordMatches=(password:string,salt:string,hash:string)=>{const actual=scryptSync(password,salt,64);const expected=Buffer.from(hash,"hex");return actual.length===expected.length&&timingSafeEqual(actual,expected);};
const toAccount=(row:AccountRow):Account=>({id:row.id,name:row.name,type:row.type,...(row.account_number?{accountNumber:row.account_number}:{}),maskedNumber:row.masked_number,currency:row.currency,balance:dollars(row.balance_cents),availableBalance:dollars(row.available_balance_cents),...(row.interest_rate_bps===null?{}:{interestRate:row.interest_rate_bps/100})});
const generateAccountNumber=()=>randomInt(1_000_000_000,10_000_000_000).toString();
const toTransaction=(row:TransactionRow):BankTransaction=>({id:row.id,accountId:row.account_id,description:row.description,merchant:row.merchant,category:row.category,amount:dollars(row.amount_cents),direction:row.direction,status:row.status,reference:row.reference,createdAt:row.created_at});
const toCard=(row:CardRow):BankCard=>({id:row.id,accountId:row.account_id,holderName:row.holder_name,lastFour:row.last_four,network:row.network,type:row.type,status:row.status,spendingLimit:dollars(row.spending_limit_cents),expires:row.expires});

export class SQLiteStorage implements IStorage{
  readonly kind="sqlite" as const;
  readonly databasePath:string;
  private readonly db:Database.Database;

  constructor(databasePath=process.env.CLIPX_DATABASE_PATH||path.resolve(import.meta.dirname,"../../../clipx.db")){
    this.databasePath=databasePath;
    this.db=new Database(databasePath);
    this.db.pragma("journal_mode = WAL");
    this.db.pragma("foreign_keys = ON");
    this.migrate();
    this.ensureLegacyCredentials();
  }

  private migrate(){this.db.exec(`
    CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,first_name TEXT NOT NULL,last_name TEXT NOT NULL,profile_image_url TEXT,is_admin INTEGER NOT NULL DEFAULT 0,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,last_active_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS accounts (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN ('checking','savings')),account_number TEXT UNIQUE CHECK(account_number IS NULL OR (length(account_number)=10 AND account_number NOT GLOB '*[^0-9]*')),masked_number TEXT NOT NULL,currency TEXT NOT NULL DEFAULT 'USD',balance_cents INTEGER NOT NULL,available_balance_cents INTEGER NOT NULL,interest_rate_bps INTEGER);
    CREATE TABLE IF NOT EXISTS transactions (id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,description TEXT NOT NULL,merchant TEXT NOT NULL,category TEXT NOT NULL,amount_cents INTEGER NOT NULL CHECK(amount_cents>0),direction TEXT NOT NULL CHECK(direction IN ('credit','debit')),status TEXT NOT NULL CHECK(status IN ('completed','pending','failed')),reference TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS cards (id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,holder_name TEXT NOT NULL,last_four TEXT NOT NULL,network TEXT NOT NULL DEFAULT 'Visa',type TEXT NOT NULL CHECK(type IN ('physical','virtual')),status TEXT NOT NULL CHECK(status IN ('active','frozen')),spending_limit_cents INTEGER NOT NULL,expires TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS beneficiaries (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,bank_name TEXT NOT NULL,masked_account TEXT NOT NULL,initials TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS cash_flow (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,month TEXT NOT NULL,sort_order INTEGER NOT NULL,income_cents INTEGER NOT NULL,spending_cents INTEGER NOT NULL,PRIMARY KEY(user_id,month));
    CREATE TABLE IF NOT EXISTS user_preferences (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,transaction_alerts INTEGER NOT NULL DEFAULT 1,monthly_summary INTEGER NOT NULL DEFAULT 1,show_balances INTEGER NOT NULL DEFAULT 1);
    CREATE TABLE IF NOT EXISTS local_credentials (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
    CREATE INDEX IF NOT EXISTS idx_accounts_user ON accounts(user_id);CREATE INDEX IF NOT EXISTS idx_transactions_account_date ON transactions(account_id,created_at DESC);CREATE INDEX IF NOT EXISTS idx_beneficiaries_user ON beneficiaries(user_id);CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expires_at);
  `);
    const columns=this.db.prepare("PRAGMA table_info(accounts)").all() as Array<{name:string}>;
    if(!columns.some((column)=>column.name==="account_number"))this.db.exec("ALTER TABLE accounts ADD COLUMN account_number TEXT");
    this.db.exec(`
      CREATE UNIQUE INDEX IF NOT EXISTS idx_accounts_account_number ON accounts(account_number) WHERE account_number IS NOT NULL;
      CREATE TRIGGER IF NOT EXISTS accounts_account_number_format_insert BEFORE INSERT ON accounts
      WHEN NEW.account_number IS NOT NULL AND (length(NEW.account_number)<>10 OR NEW.account_number GLOB '*[^0-9]*')
      BEGIN SELECT RAISE(ABORT,'Account numbers must contain exactly 10 digits'); END;
      CREATE TRIGGER IF NOT EXISTS accounts_account_number_format_update BEFORE UPDATE OF account_number ON accounts
      WHEN NEW.account_number IS NOT NULL AND (length(NEW.account_number)<>10 OR NEW.account_number GLOB '*[^0-9]*')
      BEGIN SELECT RAISE(ABORT,'Account numbers must contain exactly 10 digits'); END;
      CREATE TRIGGER IF NOT EXISTS accounts_account_number_immutable BEFORE UPDATE OF account_number, masked_number ON accounts
      WHEN OLD.account_number IS NOT NULL AND (NEW.account_number IS NOT OLD.account_number OR NEW.masked_number<>substr(OLD.account_number,-4))
      BEGIN SELECT RAISE(ABORT,'Account numbers cannot be changed once assigned'); END;
    `);
  }

  private ensureLegacyCredentials(){const rows=this.db.prepare("SELECT u.id FROM users u LEFT JOIN local_credentials c ON c.user_id=u.id WHERE c.user_id IS NULL").all() as Array<{id:string}>;const insert=this.db.prepare("INSERT INTO local_credentials (user_id,password_hash,password_salt,updated_at) VALUES (?,?,?,?)");this.db.transaction(()=>{for(const row of rows){const credential=createPasswordHash(process.env.CLIPX_DEFAULT_PASSWORD||"ClipXLocal123");insert.run(row.id,credential.hash,credential.salt,new Date().toISOString());}})();}
  async ping(){this.db.prepare("SELECT 1").get();}
  async getUser(id:string):Promise<User|undefined>{const row=this.db.prepare("SELECT * FROM users WHERE id=?").get(id) as UserRow|undefined;return row?{id:row.id,email:row.email,firstName:row.first_name,lastName:row.last_name,profileImageUrl:row.profile_image_url,isAdmin:Boolean(row.is_admin),isActive:Boolean(row.is_active),createdAt:row.created_at,updatedAt:row.updated_at}:undefined;}
  private getLocalUser(email:string){const row=this.db.prepare("SELECT id,email,first_name,last_name,is_admin FROM users WHERE lower(email)=lower(?)").get(email) as Pick<UserRow,"id"|"email"|"first_name"|"last_name"|"is_admin">|undefined;return row?{id:row.id,email:row.email,firstName:row.first_name,lastName:row.last_name,isAdmin:Boolean(row.is_admin)}:undefined;}
  async createLocalUser(email:string,password:string){if(this.getLocalUser(email))throw Object.assign(new Error("An account with this email already exists"),{status:409});const id=randomUUID(),normalized=email.toLowerCase(),now=new Date().toISOString(),credential=createPasswordHash(password);const localPart=normalized.split("@")[0]||"Account";const firstName=localPart.split(/[._-]/).filter(Boolean).map((part)=>`${part[0]?.toUpperCase()}${part.slice(1)}`).join(" ")||"Account";this.db.transaction(()=>{this.db.prepare("INSERT INTO users (id,email,first_name,last_name,is_admin,is_active,created_at,updated_at,last_active_at) VALUES (?,?,?,?,0,1,?,?,?)").run(id,normalized,firstName,"",now,now,now);this.db.prepare("INSERT INTO user_preferences (user_id) VALUES (?)").run(id);this.db.prepare("INSERT INTO local_credentials (user_id,password_hash,password_salt,updated_at) VALUES (?,?,?,?)").run(id,credential.hash,credential.salt,now);})();return{id,email:normalized,firstName,lastName:"",isAdmin:false};}
  async authenticateLocalUser(email:string,password:string){const row=this.db.prepare("SELECT u.id,u.email,u.first_name,u.last_name,u.is_admin,u.is_active,c.password_hash,c.password_salt FROM users u JOIN local_credentials c ON c.user_id=u.id WHERE lower(u.email)=lower(?)").get(email) as {id:string;email:string;first_name:string;last_name:string;is_admin:number;is_active:number;password_hash:string;password_salt:string}|undefined;if(!row||!row.is_active||!passwordMatches(password,row.password_salt,row.password_hash))return undefined;this.db.prepare("UPDATE users SET last_active_at=? WHERE id=?").run(new Date().toISOString(),row.id);return{id:row.id,email:row.email,firstName:row.first_name,lastName:row.last_name,isAdmin:Boolean(row.is_admin)};}
  async createSession(userId:string,tokenHash:string,expiresAt:Date){const now=new Date().toISOString();this.db.transaction(()=>{this.db.prepare("DELETE FROM sessions WHERE expires_at<=?").run(now);this.db.prepare("INSERT INTO sessions (token_hash,user_id,expires_at,created_at) VALUES (?,?,?,?)").run(tokenHash,userId,expiresAt.toISOString(),now);})();}
  async getSessionUser(tokenHash:string):Promise<LocalAuthUser|undefined>{const row=this.db.prepare("SELECT u.id,u.email,u.first_name,u.last_name,u.is_admin FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.is_active=1").get(tokenHash,new Date().toISOString()) as Pick<UserRow,"id"|"email"|"first_name"|"last_name"|"is_admin">|undefined;return row?{id:row.id,email:row.email,firstName:row.first_name,lastName:row.last_name,isAdmin:Boolean(row.is_admin)}:undefined;}
  async deleteSession(tokenHash:string){this.db.prepare("DELETE FROM sessions WHERE token_hash=?").run(tokenHash);}
  async deleteUserSessions(userId:string){this.db.prepare("DELETE FROM sessions WHERE user_id=?").run(userId);}
  async getAccounts(userId:string){return(this.db.prepare("SELECT id,name,type,account_number,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps FROM accounts WHERE user_id=? ORDER BY type").all(userId) as AccountRow[]).map(toAccount);}
  async getTransactions(userId:string){return(this.db.prepare("SELECT t.* FROM transactions t JOIN accounts a ON a.id=t.account_id WHERE a.user_id=? ORDER BY t.created_at DESC").all(userId) as TransactionRow[]).map(toTransaction);}
  async getCards(userId:string){return(this.db.prepare("SELECT c.* FROM cards c JOIN accounts a ON a.id=c.account_id WHERE a.user_id=? ORDER BY c.type").all(userId) as CardRow[]).map(toCard);}
  async getBeneficiaries(userId:string){return(this.db.prepare("SELECT id,name,bank_name,masked_account,initials FROM beneficiaries WHERE user_id=? ORDER BY name").all(userId) as BeneficiaryRow[]).map((row)=>({id:row.id,name:row.name,bankName:row.bank_name,maskedAccount:row.masked_account,initials:row.initials}));}
  async getOverview(userId:string):Promise<BankingOverview>{const accounts=await this.getAccounts(userId);const flow=this.db.prepare("SELECT month,income_cents,spending_cents FROM cash_flow WHERE user_id=? ORDER BY sort_order").all(userId) as Array<{month:string;income_cents:number;spending_cents:number}>;const latest=flow.at(-1);return{totalBalance:accounts.reduce((sum,a)=>sum+a.balance,0),availableBalance:accounts.reduce((sum,a)=>sum+a.availableBalance,0),monthlyIncome:dollars(latest?.income_cents??0),monthlySpending:dollars(latest?.spending_cents??0),accounts,cashFlow:flow.map((row)=>({month:row.month,income:dollars(row.income_cents),spending:dollars(row.spending_cents)}))};}
  async createTransfer(userId:string,transfer:CreateTransfer){return this.db.transaction(()=>{const account=this.db.prepare("SELECT * FROM accounts WHERE id=? AND user_id=?").get(transfer.sourceAccountId,userId) as AccountRow|undefined;const beneficiary=this.db.prepare("SELECT * FROM beneficiaries WHERE id=? AND user_id=?").get(transfer.beneficiaryId,userId) as BeneficiaryRow|undefined;if(!account)throw Object.assign(new Error("Source account not found"),{status:404});if(!beneficiary)throw Object.assign(new Error("Recipient not found"),{status:404});const amount=cents(transfer.amount);if(account.available_balance_cents<amount)throw Object.assign(new Error("Insufficient available balance"),{status:422});this.db.prepare("UPDATE accounts SET balance_cents=balance_cents-?,available_balance_cents=available_balance_cents-? WHERE id=?").run(amount,amount,account.id);const row:TransactionRow={id:randomUUID(),account_id:account.id,description:transfer.note||"Bank transfer",merchant:beneficiary.name,category:"transfer",amount_cents:amount,direction:"debit",status:"completed",reference:`TRF-${randomBytes(5).toString("hex").toUpperCase()}`,created_at:new Date().toISOString()};this.db.prepare("INSERT INTO transactions (id,account_id,description,merchant,category,amount_cents,direction,status,reference,created_at) VALUES (@id,@account_id,@description,@merchant,@category,@amount_cents,@direction,@status,@reference,@created_at)").run(row);return toTransaction(row);})();}
  async updateCard(userId:string,cardId:string,update:UpdateCard){const row=this.db.prepare("SELECT c.* FROM cards c JOIN accounts a ON a.id=c.account_id WHERE c.id=? AND a.user_id=?").get(cardId,userId) as CardRow|undefined;if(!row)throw Object.assign(new Error("Card not found"),{status:404});this.db.prepare("UPDATE cards SET status=?,spending_limit_cents=? WHERE id=?").run(update.status??row.status,update.spendingLimit===undefined?row.spending_limit_cents:cents(update.spendingLimit),cardId);return toCard(this.db.prepare("SELECT * FROM cards WHERE id=?").get(cardId) as CardRow);}
  async getSettings(userId:string):Promise<AccountSettings>{const row=this.db.prepare("SELECT u.email,u.first_name,u.last_name,p.transaction_alerts,p.monthly_summary,p.show_balances FROM users u JOIN user_preferences p ON p.user_id=u.id WHERE u.id=?").get(userId) as {email:string;first_name:string;last_name:string;transaction_alerts:number;monthly_summary:number;show_balances:number}|undefined;if(!row)throw Object.assign(new Error("Account settings not found"),{status:404});return{profile:{firstName:row.first_name,lastName:row.last_name,email:row.email},preferences:{transactionAlerts:Boolean(row.transaction_alerts),monthlySummary:Boolean(row.monthly_summary),showBalances:Boolean(row.show_balances)}};}
  async updateProfile(userId:string,update:UpdateProfile){const result=this.db.prepare("UPDATE users SET first_name=?,last_name=?,updated_at=? WHERE id=?").run(update.firstName,update.lastName,new Date().toISOString(),userId);if(!result.changes)throw Object.assign(new Error("Account not found"),{status:404});this.db.prepare("UPDATE cards SET holder_name=? WHERE account_id IN (SELECT id FROM accounts WHERE user_id=?)").run(`${update.firstName} ${update.lastName}`.toUpperCase(),userId);return this.getSettings(userId);}
  async updatePreferences(userId:string,update:UpdatePreferences){const current=(await this.getSettings(userId)).preferences;this.db.prepare("UPDATE user_preferences SET transaction_alerts=?,monthly_summary=?,show_balances=? WHERE user_id=?").run(Number(update.transactionAlerts??current.transactionAlerts),Number(update.monthlySummary??current.monthlySummary),Number(update.showBalances??current.showBalances),userId);return this.getSettings(userId);}
  async changePassword(userId:string,update:ChangePassword){const row=this.db.prepare("SELECT password_hash,password_salt FROM local_credentials WHERE user_id=?").get(userId) as {password_hash:string;password_salt:string}|undefined;if(!row||!passwordMatches(update.currentPassword,row.password_salt,row.password_hash))throw Object.assign(new Error("Current password is incorrect"),{status:401});const credential=createPasswordHash(update.newPassword);this.db.prepare("UPDATE local_credentials SET password_hash=?,password_salt=?,updated_at=? WHERE user_id=?").run(credential.hash,credential.salt,new Date().toISOString(),userId);}
  async getAdminStats():Promise<AdminStats>{const counts=this.db.prepare("SELECT COUNT(*) total,COALESCE(SUM(CASE WHEN is_active=1 THEN 1 ELSE 0 END),0) active FROM users WHERE is_admin=0").get() as {total:number;active:number};const balance=this.db.prepare("SELECT COALESCE(SUM(balance_cents),0) value FROM accounts").get() as {value:number};const volume=this.db.prepare("SELECT COALESCE(SUM(amount_cents),0) value FROM transactions WHERE status='completed'").get() as {value:number};const pending=this.db.prepare("SELECT COUNT(*) value FROM transactions WHERE status='pending'").get() as {value:number};return{totalCustomers:counts.total,activeCustomers:counts.active,managedBalance:dollars(balance.value),processedVolume:dollars(volume.value),pendingTransactions:pending.value,systemStatus:"operational"};}
  async getAdminUsers():Promise<AdminCustomer[]>{const rows=this.db.prepare("SELECT u.*,COALESCE(SUM(a.balance_cents),0) balance_cents FROM users u LEFT JOIN accounts a ON a.user_id=u.id GROUP BY u.id ORDER BY u.last_active_at DESC").all() as Array<UserRow&{balance_cents:number}>;return rows.map((row)=>({id:row.id,email:row.email,firstName:row.first_name,lastName:row.last_name,initials:`${row.first_name[0]??""}${row.last_name[0]??""}`||"CX",isAdmin:Boolean(row.is_admin),isActive:Boolean(row.is_active),balance:dollars(row.balance_cents),createdAt:row.created_at,lastActiveAt:row.last_active_at}));}
  async createAdminUser(input:CreateAdminCustomer){if(this.db.prepare("SELECT 1 FROM users WHERE lower(email)=lower(?)").get(input.email))throw Object.assign(new Error("Another account already uses this email"),{status:409});const userId=randomUUID(),now=new Date().toISOString(),credential=createPasswordHash(input.password);this.db.transaction(()=>{this.db.prepare("INSERT INTO users (id,email,first_name,last_name,is_admin,is_active,created_at,updated_at,last_active_at) VALUES (?,?,?,?,?,?,?,?,?)").run(userId,input.email.toLowerCase(),input.firstName,input.lastName,Number(input.isAdmin),Number(input.isActive),now,now,now);this.db.prepare("INSERT INTO user_preferences (user_id) VALUES (?)").run(userId);this.db.prepare("INSERT INTO local_credentials (user_id,password_hash,password_salt,updated_at) VALUES (?,?,?,?)").run(userId,credential.hash,credential.salt,now);if(input.account){const balance=cents(input.account.openingBalance);this.db.prepare("INSERT INTO accounts (id,user_id,name,type,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps) VALUES (?,?,?,?,?,'USD',?,?,NULL)").run(randomUUID(),userId,input.account.name,input.account.type,input.account.maskedNumber,balance,balance);}})();const customer=(await this.getAdminUsers()).find((item)=>item.id===userId);if(!customer)throw Object.assign(new Error("Customer could not be created"),{status:500});return customer;}
  async getAdminUserDetails(userId:string):Promise<AdminCustomerDetails>{const customer=(await this.getAdminUsers()).find((item)=>item.id===userId);if(!customer)throw Object.assign(new Error("Customer not found"),{status:404});const settings=await this.getSettings(userId);return{customer,accounts:await this.getAccounts(userId),cards:await this.getCards(userId),transactions:(await this.getAdminTransactions()).filter((item)=>item.customerId===userId),preferences:settings.preferences};}
  async updateAdminUser(userId:string,update:UpdateAdminUser){const row=this.db.prepare("SELECT email,first_name,last_name,is_admin,is_active FROM users WHERE id=?").get(userId) as {email:string;first_name:string;last_name:string;is_admin:number;is_active:number}|undefined;if(!row)throw Object.assign(new Error("Customer not found"),{status:404});const email=(update.email??row.email).toLowerCase();if(this.db.prepare("SELECT 1 FROM users WHERE lower(email)=lower(?) AND id<>?").get(email,userId))throw Object.assign(new Error("Another account already uses this email"),{status:409});const wasActive=Boolean(row.is_active),isActive=update.isActive??wasActive;this.db.transaction(()=>{this.db.prepare("UPDATE users SET email=?,first_name=?,last_name=?,is_admin=?,is_active=?,updated_at=? WHERE id=?").run(email,update.firstName??row.first_name,update.lastName??row.last_name,Number(update.isAdmin??Boolean(row.is_admin)),Number(isActive),new Date().toISOString(),userId);if(!wasActive||!isActive)this.db.prepare("DELETE FROM sessions WHERE user_id=?").run(userId);})();const customer=(await this.getAdminUsers()).find((item)=>item.id===userId);if(!customer)throw Object.assign(new Error("Customer not found"),{status:404});return customer;}
  async createAdminAccount(userId:string,input:CreateAdminAccount){if(!this.db.prepare("SELECT 1 FROM users WHERE id=?").get(userId))throw Object.assign(new Error("Customer not found"),{status:404});const balance=cents(input.openingBalance),accountId=randomUUID();this.db.prepare("INSERT INTO accounts (id,user_id,name,type,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps) VALUES (?,?,?,?,?,'USD',?,?,NULL)").run(accountId,userId,input.name,input.type,input.maskedNumber,balance,balance);return toAccount(this.db.prepare("SELECT id,name,type,account_number,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps FROM accounts WHERE id=?").get(accountId) as AccountRow);}
  async updateAdminAccount(userId:string,accountId:string,update:UpdateAdminAccount){const row=this.db.prepare("SELECT id,name,type,account_number,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps FROM accounts WHERE id=? AND user_id=?").get(accountId,userId) as AccountRow|undefined;if(!row)throw Object.assign(new Error("Customer account not found"),{status:404});if(row.account_number&&update.maskedNumber!==undefined&&update.maskedNumber!==row.masked_number)throw Object.assign(new Error("The final four digits are locked after an account number is assigned"),{status:409});this.db.prepare("UPDATE accounts SET name=?,type=?,masked_number=? WHERE id=? AND user_id=?").run(update.name??row.name,update.type??row.type,update.maskedNumber??row.masked_number,accountId,userId);return toAccount(this.db.prepare("SELECT id,name,type,account_number,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps FROM accounts WHERE id=?").get(accountId) as AccountRow);}
  async assignAdminAccountNumber(userId:string,accountId:string){const existing=this.db.prepare("SELECT id,name,type,account_number,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps FROM accounts WHERE id=? AND user_id=?").get(accountId,userId) as AccountRow|undefined;if(!existing)throw Object.assign(new Error("Customer account not found"),{status:404});if(existing.account_number)throw Object.assign(new Error("An account number has already been assigned and cannot be changed"),{status:409});for(let attempt=0;attempt<5;attempt+=1){try{const number=generateAccountNumber();const result=this.db.prepare("UPDATE accounts SET account_number=?,masked_number=? WHERE id=? AND user_id=? AND account_number IS NULL").run(number,number.slice(-4),accountId,userId);if(!result.changes)throw Object.assign(new Error("An account number has already been assigned and cannot be changed"),{status:409});return toAccount(this.db.prepare("SELECT id,name,type,account_number,masked_number,currency,balance_cents,available_balance_cents,interest_rate_bps FROM accounts WHERE id=?").get(accountId) as AccountRow);}catch(error){if(error&&typeof error==="object"&&"code" in error&&error.code==="SQLITE_CONSTRAINT_UNIQUE")continue;throw error;}}throw Object.assign(new Error("A unique account number could not be allocated. Try again."),{status:503});}
  async getAdminTransactions():Promise<AdminTransaction[]>{const rows=this.db.prepare("SELECT t.*,u.id customer_id,trim(u.first_name||' '||u.last_name) customer_name FROM transactions t JOIN accounts a ON a.id=t.account_id JOIN users u ON u.id=a.user_id ORDER BY t.created_at DESC").all() as Array<TransactionRow&{customer_id:string;customer_name:string}>;return rows.map((row)=>({...toTransaction(row),customerId:row.customer_id,customerName:row.customer_name,risk:row.amount_cents>=cents(2500)||row.status==="failed"?"review":"standard"}));}
}
